language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install python-coveralls
env:
- SETTINGS='config.TestConfig'
script:
- source ./environment_test.sh
- py.test --cov introductions tests/ --cov-report=term --cov-report=html
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: EI4cSW0Ld7KIsTlXRgL5HYliuoH2Lhz9odHfa2U+ghK+ljymYMksSzJMMYHFK0ttd2FupFVo6qqQbhANQSyrLZjRPJU+U51HhGTqOKnu9wDvC7vsBAi4GuZJvNlRQ7fSyh+PrAHRC4JVayxDxjX0cP9aFHwJrfMIV4iaLr12lfo=
  app: lr-introduction-service
  on:
    repo: LandRegistry/introductions
