language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install python-coveralls
env:
- SETTINGS='config.TestConfig'
script:
- source ./environment_test.sh
- py.test --cov introductions tests/ --cov-report=term --cov-report=html
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: dp9B85UqPyN0H25mjuOHT78tTAnBJUwYU+ZePkaAUjSuTQMMhpJsU8E/X4z3YNcf5HrHbBPu0BGlTB2FkJfhSRojfNBMFNa58CskrT07pA2xCfGsDCVL5eyc2iXDTdpMb/y9lxGiP/RGEqgQF/N+fnH5CI+e8hD//X3a0PqyBZM=
  app: lr-introduction-service
  on:
    repo: LandRegistry/introductions
    branch: master
    run: "python manage.py db upgrade"
