"""empty message

Revision ID: 1f03d3f6086d
Revises: b851d7566c3
Create Date: 2014-09-18 18:09:11.859925

"""

# revision identifiers, used by Alembic.
revision = '1f03d3f6086d'
down_revision = 'b851d7566c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conveyancer', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conveyancer', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('relationship', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relationship', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conveyancer', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('conveyancer', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
