"""empty message

Revision ID: 34768175f672
Revises: None
Create Date: 2014-09-04 22:20:14.940536

"""

# revision identifiers, used by Alembic.
revision = '34768175f672'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conveyancer',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('lrid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('client',
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lrid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('confirmed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['conveyancer.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    op.drop_table('conveyancer')
    ### end Alembic commands ###
